DELETE http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTQ4NjY0NzAsInVzZXJJRCI6MX0.wdym3RJqu3ku30cD-6QfTXGZ_bjSFaJkH3WjFRNZ0ns

