POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTQ4NjU4MTgsInVzZXJJRCI6MX0.pfDCWoDRWlGbAicf12yRIOn2eBJv_1ps7RVznW77CT0

{
    "name": "Test event ",
    "description": "A test event ",
    "location": "A test location ",
    "dateTime": "2025-01-01T04:30:00.000Z"
}